import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
const statusCards = [
    { label: "New requests", value: "0" },
    { label: "Pending review", value: "0" },
    { label: "Scheduled", value: "0" },
];
export default function App() {
    return (_jsxs("main", { className: "oms-shell", children: [_jsx("div", { className: "staging-banner", children: "STAGING / DEMO" }), _jsxs("header", { className: "topbar", children: [_jsxs("div", { children: [_jsx("p", { className: "eyebrow", children: "JustCocon OMS" }), _jsx("h1", { children: "Operations management" })] }), _jsx("div", { className: "mode-chip", children: "Demo mode" })] }), _jsxs("nav", { className: "nav-panel", "aria-label": "Main navigation", children: [_jsx("button", { type: "button", children: "Overview" }), _jsx("button", { type: "button", children: "Bookings" }), _jsx("button", { type: "button", children: "Staff review" }), _jsx("button", { type: "button", children: "Scheduling" })] }), _jsx("section", { className: "stats-grid", "aria-label": "Booking overview", children: statusCards.map((card) => (_jsxs("article", { className: "stat-card", children: [_jsx("span", { children: card.label }), _jsx("strong", { children: card.value })] }, card.label))) }), _jsxs("section", { className: "panel-grid", children: [_jsxs("article", { className: "panel", children: [_jsx("h2", { children: "Booking overview" }), _jsx("p", { className: "placeholder-text", children: "No live booking data is connected in this demo." }), _jsx("div", { className: "empty-list", children: _jsx("p", { children: "No bookings yet" }) })] }), _jsxs("article", { className: "panel", children: [_jsx("h2", { children: "Pending staff review" }), _jsx("p", { className: "placeholder-text", children: "Manual review queue placeholder only." })] })] }), _jsxs("section", { className: "details-panel", children: [_jsx("h2", { children: "Booking details" }), _jsx("p", { className: "placeholder-text", children: "Select a booking to view details or update status." })] }), _jsxs("section", { className: "details-panel", children: [_jsx("h2", { children: "Status management" }), _jsx("p", { className: "placeholder-text", children: "Status actions are intentionally disabled in staging." })] })] }));
}
